### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by robertshum** [garrickhenne/tenant#46]
Could put anything we want, doesn't need routes.

Would be kinda cool to do our presentation slides in this section.

**Comment by dantan380** [comment]
- [ ] Insert entire final presentation as bullet points
- [ ] Insert screenshots related to bullet points (KANBAN, figma, ERD)
- [ ] Insert logos for techstack (TypeScript, MongoDB, Tailwind, Express, NodeJS, Google Natural Language, MapBox, Framer-Motion)
