### ISSUE TITLE
DB Reset Script Update

### ISSUE THREAD

**Issue by dantan380** [garrickhenne/tenant#53]
added scrooge mcduck as the scorned landlord, and nally

postal codes have '-'

populate the overallScore for fake reviews.

Create review about lecturers (Nally)
Funny review to show as example:

- [x] Always in attic
- [x] hear light singing and guitar strumming
- [x] hear 'team semi-colon' at least once per day
- [x] Has a dog named 'Snoopy' which is always a delight to see

**Comment by robertshum** [comment]
Rambles about Monkey Fuzz once in a while.
